name: instamojo
description: Instamojo SDK from Instamojo ported to flutter as plugin with all necessary features and with Null Safety which is implementation by EvilRATT
version: 1.0.0+2
homepage: https://github.com/evilrat/instamojo
repository: https://github.com/evilrat/instamojo
issue_tracker: https://github.com/evilrat/instamojo/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_bloc: ^7.3.3
  http: ^0.13.4
  meta: ^1.7.0
  equatable: ^2.0.3
  flutter_inappwebview: ^5.3.2
  decimal: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.evilratt.instamjo.instamojo
        pluginClass: InstamojoPlugin
      ios:
        pluginClass: InstamojoPlugin
      web:
        pluginClass: InstamojoWeb
        fileName: instamojo_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg